### ISSUE TITLE
Remove Content-Type header from the output?

### ISSUE THREAD

**Issue by adam-drozdz-ie** [s00d/request-templater#1]
Hello,
I need library for generating request examples, this one looks promising, however it seems to enforce the `Content-Type` header in the output even when it's not required.
I tried setting the `mimeType` to null hoping that it'd resolve the issue, but it didn't.
For example, for this input:
```
const requestTemplater = new RequestTemplater();
requestTemplater.baseUrl('https://example.com/api')
.method('GET')
.mimeType(null)
.url('users/123')
.params([
{ in: 'query', name: 'page', value: '1' },
{ in: 'query', name: 'limit', value: '10' },
{ in: 'headers', name: 'Authorization', value: 'Bearer xxxxxxxxxxxx' }
]);
const code = requestTemplater.lang('bash').library('curl').generate();
console.log(code);
```
The output is:
```
curl -X GET
-H "Content-Type: "
    -H "Authorization: Bearer xxxxxxxxxxxx"
"https://example.com/api/users/123?page=1&limit=10"
```
^ the `Content-Type` header is still there, it's just empty. Is there a way to generate code without this header?

**Comment by s00d** [comment]
hello. The issue is with the templates. I've fixed part of it in version 1.3.3, but unfortunately, I don't have time to fix all the templates right now. You can fix the ones you need by analogy and create a pull request. There are still some problems in the templates. If you find anything else, please let me know

https://github.com/s00d/request-templater/commit/912ea88b0f3c0dcb79846354243253baeee1a35a
https://github.com/s00d/request-templater/tree/main/src/templates
